#!/usr/bin/env bash
# bootstrap-zitadel.sh — bring up a fresh Zitadel instance, provision it
# (project + roles + API app + service users + pre-userinfo action) using
# the self-contained setup-sdk in this directory, and emit an env file
# ready for zitadel-grpc-auth integration tests and the greeter example.
#
#   Usage:
#     ./scripts/bootstrap-zitadel.sh         # bring up + provision
#     ./scripts/bootstrap-zitadel.sh down    # tear down + wipe state
#     ./scripts/bootstrap-zitadel.sh reset   # down then up (clean slate)
#
# Outputs (all under scripts/, all gitignored):
#   scripts/pat/admin.pat            # admin PAT minted by Zitadel on first boot
#   scripts/.env                     # env consumed by setup-sdk/main.go
#   scripts/generated-config.json    # full provisioning result (jq-friendly)
#   scripts/zitadel-test.env         # sourceable env for tests / examples
#
# Requirements: docker (24+), docker compose v2, jq, curl, go.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Host port Zitadel listens on. Override via env to avoid 8080 collisions.
# This MUST be a single value used everywhere: the docker-compose published
# port, the container's internal listen port, the EXTERNALPORT advertised
# in tokens, and the port the bootstrap script + setup-sdk dial.
export ZITADEL_HOST_PORT="${ZITADEL_HOST_PORT:-8080}"

COMPOSE="docker compose -f $SCRIPT_DIR/docker-compose.yml -p zga"

PAT_DIR="$SCRIPT_DIR/pat"
PAT_FILE="$PAT_DIR/admin.pat"
SETUP_DIR="$SCRIPT_DIR/setup-sdk"
SETUP_ENV="$SCRIPT_DIR/.env"
GENERATED_CFG="$SCRIPT_DIR/generated-config.json"
ENV_OUT="$SCRIPT_DIR/zitadel-test.env"

log()  { printf '\033[1;34m[bootstrap]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[bootstrap]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[bootstrap]\033[0m %s\n' "$*" >&2; exit 1; }

require() {
  command -v "$1" >/dev/null 2>&1 || die "missing required tool: $1"
}

cmd_down() {
  log "stopping stack and wiping volumes…"
  $COMPOSE down -v --remove-orphans || true
  rm -rf "$PAT_DIR" "$ENV_OUT" "$SETUP_ENV" "$GENERATED_CFG"
  # Kill any leftover greeter example server — it would still be holding
  # the previous run's INTROSPECT_ID/SECRET and would fail with
  # "unauthorized_client" against the freshly-provisioned Zitadel.
  if command -v lsof >/dev/null 2>&1; then
    local stale
    stale="$(lsof -tiTCP:50061 -sTCP:LISTEN 2>/dev/null || true)"
    if [[ -n "$stale" ]]; then
      log "killing stale greeter server on :50061 (pid $stale)"
      kill -9 $stale 2>/dev/null || true
    fi
  fi
  log "down."
}

wait_for_pat() {
  log "waiting for first-instance PAT to be written…"
  for _ in $(seq 1 60); do
    if [[ -s "$PAT_FILE" ]]; then
      log "PAT ready: $PAT_FILE"
      return 0
    fi
    sleep 2
  done
  die "PAT was not written within 120s. Check: $COMPOSE logs zitadel"
}

wait_for_http() {
  log "waiting for Zitadel HTTP to answer on :$ZITADEL_HOST_PORT…"
  for _ in $(seq 1 60); do
    if curl -fsS -o /dev/null "http://localhost:$ZITADEL_HOST_PORT/debug/ready"; then
      log "Zitadel is ready."
      return 0
    fi
    sleep 2
  done
  # /debug/ready isn't exposed on every release; the PAT-file check is the
  # actual readiness signal so we don't fail hard here.
  warn "/debug/ready never returned 200 — falling back to PAT-file readiness"
}

run_setup_sdk() {
  [[ -d "$SETUP_DIR" ]] || die "expected $SETUP_DIR to exist"
  local pat
  pat="$(tr -d '\n\r' < "$PAT_FILE")"

  log "writing $SETUP_ENV with bootstrap PAT…"
  cat > "$SETUP_ENV" <<EOF
# Auto-generated by scripts/bootstrap-zitadel.sh — consumed by setup-sdk/main.go
ZITADEL_ADMIN_PAT=$pat
ZITADEL_DOMAIN=localhost
ZITADEL_PORT=$ZITADEL_HOST_PORT
ZITADEL_INSECURE=true
EOF

  if [[ -f "$GENERATED_CFG" ]]; then
    log "removing stale $GENERATED_CFG"
    rm -f "$GENERATED_CFG"
  fi

  log "running setup-sdk (project, roles, API app, users, action)…"
  ( cd "$SETUP_DIR" && go run . )

  [[ -f "$GENERATED_CFG" ]] \
    || die "setup-sdk did not produce $GENERATED_CFG"
}

emit_test_env() {
  log "emitting $ENV_OUT for zitadel-grpc-auth integration tests…"

  local api_id api_secret project_id
  api_id="$(jq -r '.api_app.client_id'     "$GENERATED_CFG")"
  api_secret="$(jq -r '.api_app.client_secret' "$GENERATED_CFG")"
  project_id="$(jq -r '.project_id'        "$GENERATED_CFG")"

  {
    echo "# Auto-generated by scripts/bootstrap-zitadel.sh"
    echo "# Source this file before running integration tests:"
    echo "#   set -a && source scripts/zitadel-test.env && set +a"
    echo ""
    echo "# --- module/server config (server.Config + greeter example) ---"
    echo "export AUTH_ENABLED=true"
    echo "export ZITADEL_ISSUER=http://localhost:$ZITADEL_HOST_PORT"
    echo "export ZITADEL_INSECURE=true"
    echo "export INTROSPECT_ID=$api_id"
    echo "export INTROSPECT_SECRET=$api_secret"
    echo "export PROJECT_ID=$project_id"
    echo ""
    echo "# --- per-user client-credentials (client.Config) ---"
    jq -r '
      .users
      | to_entries[]
      | "export "
        + (.key | ascii_upcase) + "_CLIENT_ID="     + (.value.client_id | @sh) + "\n"
        + "export "
        + (.key | ascii_upcase) + "_CLIENT_SECRET=" + (.value.client_secret | @sh)
    ' "$GENERATED_CFG"
  } > "$ENV_OUT"

  log "wrote $ENV_OUT"
}

port_in_use() {
  # Returns 0 (true) if some process on this host is listening on $1.
  # Tries ss first (linux default), then lsof, then a /dev/tcp probe.
  local p="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -lntH "sport = :$p" 2>/dev/null | grep -q .
    return $?
  fi
  if command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:"$p" -sTCP:LISTEN -P -n >/dev/null 2>&1
    return $?
  fi
  (echo > /dev/tcp/127.0.0.1/"$p") >/dev/null 2>&1
}

suggest_free_port() {
  # Walks 8090, 8091, … 8099, 18080, 18081 looking for a port nothing
  # is listening on. Returns the first hit on stdout, or empty string.
  local candidates=(8090 8091 8092 8093 8094 8095 8096 8097 8098 8099 18080 18081)
  local p
  for p in "${candidates[@]}"; do
    if ! port_in_use "$p"; then
      printf '%s' "$p"
      return 0
    fi
  done
  return 1
}

preflight_port() {
  if ! port_in_use "$ZITADEL_HOST_PORT"; then
    return 0
  fi

  warn "host TCP port $ZITADEL_HOST_PORT is already in use."
  # Try to attribute the conflict so the user can decide whether to
  # free it or just pick a different one. Both lookups must tolerate
  # empty results without tripping `set -euo pipefail`.
  if command -v lsof >/dev/null 2>&1; then
    local holder=""
    holder="$(lsof -iTCP:"$ZITADEL_HOST_PORT" -sTCP:LISTEN -P -n 2>/dev/null | tail -n +2 || true)"
    if [[ -n "$holder" ]]; then
      printf '\nHolder (lsof):\n%s\n' "$holder" >&2
    fi
  fi
  if command -v docker >/dev/null 2>&1; then
    local cont=""
    cont="$(docker ps --filter "publish=$ZITADEL_HOST_PORT" --format '  {{.Names}} ({{.Image}})' 2>/dev/null || true)"
    if [[ -n "$cont" ]]; then
      printf '\nAlready bound by Docker container(s):\n%s\n' "$cont" >&2
    fi
  fi

  local suggested=""
  suggested="$(suggest_free_port 2>/dev/null || true)"
  if [[ -n "$suggested" ]]; then
    cat >&2 <<EOF

Re-run with a different host port, e.g.:

    ZITADEL_HOST_PORT=$suggested $0 ${1:-up}

(or free port $ZITADEL_HOST_PORT and retry)
EOF
  else
    cat >&2 <<EOF

Free port $ZITADEL_HOST_PORT or pick another:

    ZITADEL_HOST_PORT=<free-port> $0 ${1:-up}
EOF
  fi
  exit 1
}

cmd_up() {
  require docker
  require jq
  require curl
  require go
  docker compose version >/dev/null 2>&1 || die "docker compose v2 plugin not found"

  preflight_port up

  mkdir -p "$PAT_DIR"
  # The container writes the PAT file as its own UID; make the dir
  # world-writable so the read-back works regardless of host UID.
  chmod 0777 "$PAT_DIR"

  log "starting docker compose stack (project=zga, host port=$ZITADEL_HOST_PORT)…"
  $COMPOSE up -d --wait

  wait_for_http
  wait_for_pat
  run_setup_sdk
  emit_test_env

  cat <<EOF

========================================================================
  Zitadel is up and provisioned.

  Console:        http://localhost:$ZITADEL_HOST_PORT/ui/console
  Issuer:         http://localhost:$ZITADEL_HOST_PORT
  Admin PAT:      $PAT_FILE
  Setup output:   $GENERATED_CFG
  Test env file:  $ENV_OUT

  To run zitadel-grpc-auth integration tests against this instance:

      set -a && source $ENV_OUT && set +a
      cd $MODULE_ROOT
      go test ./... -run Integration -count=1

  To run the greeter example against this instance:

      set -a && source $ENV_OUT && set +a
      go run ./examples/greeter/server &
      CLIENT_ID=\$ALICE_CLIENT_ID CLIENT_SECRET=\$ALICE_CLIENT_SECRET \\
        go run ./examples/greeter/client -op hello -name alice
      CLIENT_ID=\$ROOT_CLIENT_ID  CLIENT_SECRET=\$ROOT_CLIENT_SECRET  \\
        go run ./examples/greeter/client -op admin -name "rotate"

  To tear it all down:

      $0 down
========================================================================
EOF
}

case "${1:-up}" in
  up)    cmd_up   ;;
  down)  cmd_down ;;
  reset) cmd_down; cmd_up ;;
  *)     die "unknown command: $1 (use: up | down | reset)" ;;
esac
